---

- name: Install snap packages
  become: true
  community.general.snap:
    name:
      - nvim
      - alacritty
      - bitwarden
      - bash-language-server
      - docker
      - go
      - jq
      - kubectl
      - kubectx
      - kustomize
      - helm
      - lazygit-gm
      - pre-commit
      - tree
      - yaml-language-server
    classic: true
    state: present

- name: Get Cider Installer
  ansible.builtin.get_url:
    url: https://github.com/ciderapp/cider-releases/releases/download/v1.5.9/cider_1.5.9_amd64.snap
    dest: /tmp/cider_1.5.9_amd64.snap

- name: Install Cider
  become: true
  ansible.builtin.shell: snap install /tmp/cider_1.5.9_amd64.snap --dangerous

# --dangerous parameter not available to ansible snap module https://github.com/ansible-collections/community.general/issues/5715
# - name: Install Cider
#   become: true
#   community.general.snap:
#     name: /tmp/cider_1.5.9_amd64.snap
#     options: ['--dangerous=true']
