---

- name: Install snap packages
  community.general.snap:
  name:
    - nvim
    - bitwarden
    - bash-language-server
    - docker
    - go
    - jq
    - kubectl
    - kubectx
    - kustomize
    - helm
    - lazygit-gm
    - pre-commit
    - tree
    - yaml-language-server
  state: present

- name: Get Cider Installer
  get_url:
    url: https://github.com/ciderapp/cider-releases/releases/download/v1.5.9/cider_1.5.9_amd64.snap

- name: Install Cider
  community.general.snap
  name:
    - /tmp/cider_1.5.9_amd64.snap
