---

- name: Group by distro
  hosts: localhost
  tasks:
    - name: Group by distro
      ansible.builtin.group_by:
        key: os_{{ ansible_facts['distribution'] }}

- name: Setup all hosts
  hosts: localhost
  roles:
    - user_dirs
    - alacritty
    - nvim
    - zsh

- name: Setup macOS hosts
  hosts: os_macOS
  roles:
    - brew

- name: Setup ubuntu hosts
  hosts: os_Ubuntu

  roles:
    - apt
    - curl
    - pip
    - snap

- name: Setup krew
  hosts: localhost
  roles:
    - krew
