- name: Create User Dirs
  ansible.builtin.file:
    path: ~/{{ item }}
    state: directory
    mode: '0755'
  with_items:
    - .config
    - .kube
    - dev
    - temp
    - git

- name: Create lsp config dir
  ansible.builtin.file:
    path: ~/.config/lsp/
    state: directory
    mode: '0755'
